### ISSUE TITLE
VERSION is not found - not present in pip

### ISSUE THREAD

**Issue by cryptax** [UnknownCollections/pysmali#1]
I install with `pip3 install smali` in a virtual environment, and I can't use it:

```
[!576]$ python3
Python 3.10.4 (main, May  2 2022, 10:55:50) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from smali import SmaliFile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/axelle/softs/myvirtualenvs/pysmali-venv/lib/python3.10/site-packages/smali/__init__.py", line 7, in <module>
    with open(os.path.join(os.path.dirname(__file__), '..', 'VERSION'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/axelle/softs/myvirtualenvs/pysmali-venv/lib/python3.10/site-packages/smali/../VERSION'
```
`VERSION` is missing. If you add it manually, it works.

**Comment by robertsmd** [comment]
second.

**Comment by robertsmd** [comment]
also needs to add lines:
```
smali/lib/peekable.py
smali/lib/smali_compare.py
```
 to the SOURCES.txt for the egg.

**Comment by fan-14** [comment]
I also have the same problem, is there any solution for this error?

**Comment by muflone** [comment]
pip install git+https://github.com/UnknownCollections/pysmali.git
